[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/AnaGciaSchz"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/anagciaschz/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "youtube"
name = "Youtube"
url = "https://www.youtube.com/@anuskuskus"

[social.params]
icon = "brand-youtube"